---
title: "Layout Models for All Tasks"
author: "Angela Zoss"
date: "March 23, 2018"
output: github_document
---

```{r layout-setup}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

```{r layout-load-environment, message=FALSE}

source('LayoutSetup.R')

```

## Mixed Models

```{r}

layouts %>% filter(Task %in% c("AvgDeg","NumClust","NumHighDegree","NumLinks","NumNodes")) %>% 
  ggplot(aes(Task, LogError)) + geom_violin() + scale_y_log10()

layouts %>% filter(Task %in% c("AvgDeg","NumClust","NumHighDegree","NumLinks","NumNodes")) %>% 
  ggplot(aes(Task, LogError)) + geom_boxplot() + #scale_y_log10() +
  labs(title="Distribution of LogError for Numerical Response Tasks,\nlayout conditions")


```

### Average Degree

```{r layout-avgdeg, child = 'Layout-Models-AvgDeg.Rmd'}
```

### Betweenness Centrality

```{r layout-bc, child = 'Layout-Models-BC.Rmd'}
```

### Select Highest Degree Node

```{r layout-clickhd, child = 'Layout-Models-ClickHD.Rmd'}
```

### Percentage of Nodes in Largest Cluster

```{r layout-lgclust, child = 'Layout-Models-LgClust.Rmd'}
```

### Number of Clusters

```{r layout-numclust, child = 'Layout-Models-NumClust.Rmd'}
```

### Degree of Highest Degree Node

```{r layout-numhd, child = 'Layout-Models-NumHD.Rmd'}
```

### Number of Links

```{r layout-numlinks, child = 'Layout-Models-NumLinks.Rmd'}
```

### Number of Nodes

```{r layout-numnodes, child = 'Layout-Models-NumNodes.Rmd'}
```



